# Site
name: 'MCF'
description: 'Cooking website from a student with ambition '
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: '/MCF'
disqus: 'demowebsite'
email: 'camillelaurent35@yahoo.fr'
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    camille:
      name:           Camille
      site:           https://calaurent.github.io/MCF/
      avatar:         /assets/images/avatar1.jpg
      bio:            "Mesdammes et Messieurs, je m'appelle Laurent Camille, J'ai eu un parcours pluridisciplinaire parce que j'ai passé mon bac STI2D spécialisation information et numérique, je me suis alors orienté alors par la suitre à l'université en sciences humaines et sociales, spécialisation psychologie à Rennes. Je suis arrivées sur Clermont dans l'optique de poursuiivre mes études pour finalement comprendre que je voulais faire de la cuisine. Je me permets donc aujoud'hui de vous présenter mon chef d'oeuvre Meilleur Cuisinier de France"
      email:          camillelaurent35@yahoo.fr
    
    emmanuel:
      name:           Emmanuel
      site:           https://cv.emmanuelpierrain.fr
      avatar:         /assets/images/manu.png
      bio:            "Ingénieur informaticien, spécialisé en Réseaux et Cybersécurité, j'ai aidé Camille à concevoir ce site. Vous pouvez consulter mon CV sur mon site."
      email:          empierrain@gmail.com

# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: sal
      avatar: /assets/images/avatar1.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
